### ISSUE TITLE
KeyError: 'assets'

### ISSUE THREAD

**Issue by Sl-L** [H4KKR/pytubeX#19] opened 2020-11-13 00:54 UTC
I keep getting error when try to do this (the url is just an example):
```
from pytube import YouTube
yt = YouTube("https://www.youtube.com/watch?v=pXP2sgsfEPk")
```
Here's the error log:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
KeyError: 'assets'
>>> yt = YouTube("https://www.youtube.com/watch?v=RPMf1BKVDZg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
KeyError: 'assets'
```
Extra Info:
- OS: Microsoft Windows [Versión 10.0.19041.572]
- Python version: 3.8.5
- PyTubeX version: 0.1.4 (Problems still from 0.1.2)

**Comment by harmtemolder** [comment] 2020-11-25 16:41
This is a duplicate of #17 (although with a better issue title)

**Closed** 2021-06-22 00:31 UTC
